### ISSUE TITLE
Alteração grade: inserir palestra "Gerenciando PostgreSQL 10 com OmniDB"

### ISSUE THREAD

**Issue by lfbueno** [pgbr/www-2017#11]
inserir palestra "Gerenciando PostgreSQL 10 com OmniDB", palestrante Rafael Thofehrn Castro. Descrição: OmniDB é uma ferramenta web para gerenciamento de bancos de dados. Novas funcionalidades incluem monitoramento de replicação para publish/subscribe e suporte a Postgres-BDR e Postgres-XL. Data da palestra: 15/9; Horário: 17:00 horas.

**Comment by lucasviecelli** [comment]
Definir o dia e hora da palestra, para adicionar na grade

**Comment by lfbueno** [comment]
Data da palestra: 15/9; Horário: 17:00 horas.

**Comment by wind39** [comment]
Vai conflitar com a palestra do @sebastianwebber e com Coach Clinic, é isso mesmo?

**Comment by lfbueno** [comment]
Não é conflito, são atividades paralelas. Todas as outras palestras acontecem em horários paralelos. Coach Clinic atenderá público específico.  Confirmo a data/horário.

**Comment by wind39** [comment]
@lfbueno Me expressei mal. Quando eu disse *conflitar*, eu me referi ao fato de que já existem 2 atividades ocupando cada um dos 2 salões nesse horário.

No caso, a palestra em questão será realizada em qual salão?

**Comment by lfbueno** [comment]
Entendi. O Coach Clinic vai acontecer na sala vip destinada aos palestrantes (Charrua). A palestra do Rafael vai acontecer na Farroupilha.

**Comment by wind39** [comment]
@lfbueno Fechou, agradeço a prontidão :+1:

**Comment by wind39** [comment]
Vou tentar resolver e fazer uma PR.

**Comment by lfbueno** [comment]
Beleza pura!

**Comment by wind39** [comment]
Feito, criada PR #15

**Comment by sebastianwebber** [comment]
Fiz o merge.
